const $=id=>document.getElementById(id);
let tab='evidence',cursor=null,selection=null,query='',owner=null,editing=null,loading=0;
const plain=t=>t.replace(/\[\[(?:[^|\]]+\|)?([^\]]+)\]\]/g,'$1');
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
async function request(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function error(e){$('error').hidden=false;$('error').textContent=e.message}
async function start(){const secret=location.hash.slice(1);history.replaceState(null,'','/');if(secret){try{await request('/session',{secret})}catch{/* An already connected browser may reopen a used launch link. */}}owner=await request('/owner');$('error').hidden=true;$('setup').hidden=!owner.setup;$('workspace').hidden=!!owner.setup;if(owner.setup){$('setup-path').textContent=owner.path;return}$('vault-name').textContent=owner.name;$('identity').textContent=`${owner.handle} · owner`;$('location').textContent=owner.path;document.title=owner.name+' — Shared BigBrain';await list()}
$('setup-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button');b.disabled=true;try{await request('/owner',Object.fromEntries(new FormData(form)));await start()}catch(e){form.querySelector('.form-error').textContent=e.message}finally{b.disabled=false}};
async function list(append=false){const generation=++loading;const path=query?'/v1/search?q='+encodeURIComponent(query):`/v1/${tab}?limit=50${cursor&&append?'&cursor='+encodeURIComponent(cursor):''}${tab==='assertions'?'&include_revoked=1':''}`;const d=await request(path);if(generation!==loading)return;if(!append)$('records').replaceChildren();cursor=d.next_cursor;$('more').hidden=!cursor||!!query;const rows=d.hits||d.items;for(const row of rows){const kind=row.kind|| (row.assertion?'assertion':'evidence');const item=row.assertion||row;const title=item.text||item.title;const b=node('button',undefined,'record');b.dataset.id=item.id;b.append(node('strong',plain(title)),node('small',`${kind} · ${item.author?.id||'unknown'}${row.revocation?' · retired':''}`));b.onclick=()=>openRecord(kind,item.id);$('records').append(b)}if(!rows.length&&!append)$('records').append(node('p',query?'No matching records.':tab==='evidence'?'Add the first piece of evidence.':'Select evidence to make your first assertion.','empty'));highlight()}
function highlight(){document.querySelectorAll('.record').forEach(n=>n.classList.toggle('selected',n.dataset.id===selection?.id))}
async function openRecord(kind,id){selection={kind,id};highlight();try{const data=await request(`/v1/${kind==='evidence'?'evidence':'assertions'}/${id}`);if(selection?.id!==id)return;const e=data.evidence||data.assertion||data;const d=$('detail');d.replaceChildren();d.append(node('p',`${kind.toUpperCase()} · ${e.author?.id||''}`,'eyebrow'),node('h2',plain(e.title||e.text)),node('p',kind==='evidence'?e.body:'','body'));const actions=node('div',undefined,'actions');if(kind==='evidence'){const b=node('button','Make assertion','primary');b.onclick=()=>editor('assert',e);actions.append(b)}else{if(data.revocation){d.append(node('p','Retired · '+data.revocation.reason,'muted'));if(data.resolved_id!==id){const b=node('button','Read replacement');b.onclick=()=>openRecord('assertion',data.resolved_id);actions.append(b)}}else if(e.author.id===owner.handle){for(const [label,action]of [['Correct','correct'],['Retract','retract']]){const b=node('button',label);b.onclick=()=>editor(action,e);actions.append(b)}}d.append(node('h3','Evidence'));for(const source of e.sources){const sid=source.insertion_id;const evidence=await request('/v1/evidence/'+sid);if(selection?.id!==id)return;const doc=evidence.evidence||evidence;const b=node('button',doc.title||sid,'citation');b.onclick=()=>openRecord('evidence',sid);d.append(b)}}d.append(actions)}catch(e){error(e)}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{tab=b.dataset.tab;query='';$('search').value='';cursor=null;document.querySelectorAll('[data-tab]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));try{await list()}catch(e){error(e)}});
$('search-form').onsubmit=async e=>{e.preventDefault();query=$('search').value.trim();cursor=null;try{await list()}catch(e){error(e)}};
$('more').onclick=()=>list(true).catch(error);$('add').onclick=()=>editor('evidence');$('cancel').onclick=()=>$('editor').close();
function field(label,name,value='',area=false){const l=node('label',label),i=node(area?'textarea':'input');i.name=name;i.required=true;i.value=value;if(name==='title')i.maxLength=300;if(name==='text'||name==='reason')i.maxLength=2000;l.append(i);$('edit-fields').append(l);return i}
async function editor(action,item){editing={action,item};$('edit-fields').replaceChildren();$('edit-form').querySelector('.form-error').textContent='';$('save').textContent=action==='retract'?'Retract':'Save';$('edit-title').textContent={evidence:'Add evidence',assert:'Make an assertion',correct:'Correct assertion',retract:'Retract assertion'}[action];if(action==='evidence'){field('Title','title');field('Evidence','body','',true)}else if(action==='retract'){field('Reason','reason','',true)}else{field('Assertion','text',action==='correct'?item.text.replace(/\[\[[^|\]]+\|([^\]]+)\]\]/g,'[[$1]]'):'',true);if(action==='correct')field('Reason for correction','reason');const fs=node('fieldset');fs.append(node('legend','Supporting evidence'));$('edit-fields').append(fs);try{let page=null;const selected=action==='assert'?[item.id]:item.sources.map(s=>s.insertion_id);do{const d=await request('/v1/evidence?limit=200'+(page?'&cursor='+encodeURIComponent(page):''));for(const e of d.items){const l=node('label',undefined,'source-option'),c=node('input');c.type='checkbox';c.name='sources';c.value=e.id;c.checked=selected.includes(e.id);l.append(c,node('span',e.title));fs.append(l)}page=d.next_cursor}while(page)}catch(e){error(e);return}}$('editor').showModal()}
$('edit-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form),{action,item}=editing;const body=Object.fromEntries(fd);if(action==='assert'||action==='correct'){body.sources=fd.getAll('sources');if(!body.sources.length){form.querySelector('.form-error').textContent='Select at least one piece of evidence.';return}}$('save').disabled=true;$('cancel').disabled=true;try{const path=action==='evidence'?'/v1/evidence':action==='assert'?'/v1/assertions':`/v1/assertions/${item.id}/${action}`;const result=await request(path,body);$('editor').close();query='';$('search').value='';tab=action==='evidence'?'evidence':'assertions';document.querySelectorAll('[data-tab]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.tab===tab)));await list();await openRecord(action==='evidence'?'evidence':'assertion',action==='retract'?item.id:result.id);$('error').hidden=true}catch(e){form.querySelector('.form-error').textContent=e.message}finally{$('save').disabled=false;$('cancel').disabled=false}};
addEventListener('hashchange',()=>{if(location.hash)start().catch(error)});
start().catch(error);
