const {chromium}=require('./browserHarness.cjs');
const assert=require('node:assert/strict');
const base=process.env.SIDEBAR_PREVIEW_URL || 'http://127.0.0.1:5218';
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 await page.goto(`${base}/sidebar-workbench.html`);
 await page.waitForFunction(()=>document.documentElement.dataset.sidebarWorkbench==='closed');
 await page.keyboard.press('a');
 await page.locator('.pilot-row').first().waitFor();
 await page.getByRole('button',{name:'Show archived',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.pilot-row').length===5);
 const names=await page.locator('.pilot-row .row-heading strong').allTextContents();
 assert.equal(names.length,5);
 assert(names.includes('Atlas design review'),'recently active ingested agent stays visible');
 assert(names.includes('Earlier project review') && names.includes('Completed Atlas review'),'all sessions remain, including archived history');
 await page.locator('.pilot-row').filter({hasText:'Atlas planning'}).click();
 await page.locator('.pilot-panel').waitFor();
 const full=await page.locator('.chat-drawer').boundingBox();
 assert.equal(full.width,1440,'agent list opens a full-screen conversation');
 assert.equal(full.y,0);
 assert.equal(await page.locator('#topbar').isVisible(),false);
 assert.equal((await page.locator('.pilot-panel > header').boundingBox()).height,80);
 assert.equal(await page.locator('.pilot-panel .resize-controls').count(),0);
 assert.equal(full.x,0,'chat does not reserve sidebar space');
 assert.equal(await page.getByRole('navigation',{name:'Agent navigation'}).count(),0);
 assert.equal(await page.locator('.pilot-panel .note-history').count(),0);
 await page.locator('.pilot-panel [contenteditable=true]').evaluate(el=>el.blur());
 const route=page.url();
 await page.keyboard.press('h');await page.keyboard.press('l');
 assert.equal(page.url(),route,'H/L no longer navigate between agents or leave the conversation');
 await page.keyboard.press('r');
 await page.getByRole('textbox',{name:'Chat title',exact:true}).fill('Renamed Atlas');
 await page.keyboard.press('Enter');
 await page.getByRole('button',{name:'Rename chat',exact:true}).waitFor();
 assert((await page.locator('.chat-title').textContent()).includes('Renamed Atlas'));
 await page.getByRole('button',{name:'Rename chat',exact:true}).click();
 await page.getByRole('textbox',{name:'Chat title',exact:true}).fill('Cancel this');
 await page.keyboard.press('Escape');
 assert((await page.locator('.chat-title').textContent()).includes('Renamed Atlas'));
 const editor = page.locator('.pilot-panel [contenteditable=true]');
 assert.equal(await editor.getAttribute('data-input-hint'),null);
 assert.equal(await page.locator('.composer-talk').count(),0);
 assert.equal(await editor.evaluate(el=>el===document.activeElement),true,'composer focuses after opening and renaming');
 // Native macOS text editing must reach the browser without app cancellation.
 const intercepted = await editor.evaluate(el=>{
   return ['k','e','d'].map(key=>{
     const event=new KeyboardEvent('keydown',{key,ctrlKey:true,bubbles:true,cancelable:true});
     el.dispatchEvent(event); return event.defaultPrevented;
   });
 });
 assert.deepEqual(intercepted,[false,false,false]);
 await page.keyboard.press('Meta+k');
 assert.equal(await editor.evaluate(el=>el===document.activeElement),true,'Cmd-K keeps focus in composer');
 assert.equal(await page.getByRole('combobox',{name:'Search the vault'}).count(),0);
 await editor.fill('alpha beta');
 await page.keyboard.press('Control+a');
 await page.keyboard.press('Control+d');
 await page.keyboard.press('Control+e');
 await page.keyboard.type('!');
 if(process.platform==='darwin') assert.equal(await editor.textContent(),'lpha beta!');
 await page.keyboard.press('Control+a');
 await page.keyboard.press('Control+k');
 if(process.platform==='darwin') assert.equal(await editor.textContent(),'');
 await editor.fill('Keep this draft');
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>location.hash==='#/home' && document.documentElement.dataset.sidebarWorkbench==='closed');
 assert.equal(await page.locator('.pilots-pane').count(),0);
 assert.equal(await page.locator('.workspace-menu').count(),0);
 assert.equal(await page.locator('html').getAttribute('data-sidebar-hidden'),'true');
 await page.keyboard.press('a');
 await page.locator('.pilot-row').filter({hasText:'Renamed Atlas'}).click();
 await page.locator('.pilot-panel').waitFor();
 assert.equal(await page.locator('.pilot-panel [contenteditable=true]').textContent(),'Keep this draft');
 await page.getByRole('button',{name:'Close conversation',exact:true}).click();
 await page.waitForFunction(()=>document.documentElement.dataset.sidebarWorkbench==='closed');
 assert.equal(await page.locator('.pilots-pane').count(),0);
 await page.keyboard.press('a');
 await page.locator('.pilot-row').first().waitFor();
 await page.evaluate(async()=>{
   const later=Date.now()+13*60*60*1000;
   Date.now=()=>later;
   const {refreshChats}=await import('/src/lib/pilotChat.svelte.ts');
   await refreshChats();
 });
 assert.equal(await page.locator('.pilot-row').count(),5,'time alone never removes an agent');
 await page.locator('.pilot-row').filter({hasText:'Renamed Atlas'}).click();
 await page.locator('.pilot-panel').waitFor();
 await page.keyboard.press('Shift+Escape');
 await page.waitForFunction(()=>document.documentElement.dataset.sidebarWorkbench==='closed');
 await page.keyboard.press('a');
 await page.locator('.pilot-row').first().waitFor();
 assert.equal(await page.locator('.pilot-row').count(),5,'Shift-Escape retains the archived agent in history');
 await page.locator('.pilot-row').filter({hasText:'Component audit'}).click();
 await page.getByRole('button',{name:'Archive Pilot',exact:true}).click();
 await page.waitForFunction(()=>document.documentElement.dataset.sidebarWorkbench==='closed');
 await page.keyboard.press('a');
 await page.waitForFunction(()=>document.querySelectorAll('.pilot-row').length===5);
 await page.getByRole('button',{name:/Renamed Atlas.*, Archived$/}).waitFor();
 await page.getByRole('button',{name:/Component audit.*, Archived$/}).waitFor();
 console.log('Persistent roster, inline rename, input focus styling, direct Escape, explicit stop and retained draft passed.');
}finally{await browser.close();}})();
