const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 await page.goto('http://127.0.0.1:5204/sidebar-workbench.html');
 await page.keyboard.press('a');await page.locator('.pilot-row').first().click();
 const editor=page.locator('.pilot-panel [contenteditable=true]');await editor.focus();
 const local=page.getByRole('button',{name:'Leave message input'});
 assert(await local.isVisible());assert(!(await page.locator('.sidebar-close').isVisible()));
 assert(await page.locator('.composer-actions').isVisible());
 const before=await editor.boundingBox();
 await page.keyboard.press('Escape');
 assert(!(await local.isVisible()));assert(!(await page.locator('.composer-actions').isVisible()));
 assert(await page.locator('.sidebar-close').isVisible());
 assert.deepEqual(await editor.boundingBox(),before);
 await editor.fill('A new message');await editor.focus();
 await page.locator('.composer-actions button').click();
 await page.getByText('A new message',{exact:true}).waitFor();
 await editor.focus();await local.click();assert(await page.locator('.sidebar-close').isVisible());
 await page.keyboard.press('Escape');await page.locator('.pilots-pane').waitFor();
 console.log('Composer Escape ownership, hidden Send, stable layout, mouse send and return navigation passed.');
}finally{await browser.close();}})();
