const {chromium}=require('./browserHarness.cjs');
const assert=require('node:assert/strict');
const base=process.env.SIDEBAR_PREVIEW_URL||'http://127.0.0.1:5219';
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${base}/sidebar-workbench.html?managed-clients=1&legacy-clients=1&revoked-legacy-clients=1#/settings/connected-clients`);
 await page.getByText('Existing connections',{exact:true}).waitFor();
 await page.getByText('Codex on sample laptop',{exact:true}).waitFor();
 assert.equal(await page.getByText('Retired Codex plugin',{exact:true}).count(),0,'revoked legacy connections stay hidden on initial load');
 assert.equal(await page.getByText('Orchestration: Codex',{exact:true}).count(),0,'managed clients stay out of Connected Clients');
 assert.equal(await page.getByLabel('Connection name').count(),0,'new connection form starts collapsed');
 await page.getByRole('button',{name:'New connection +',exact:true}).click();
 await page.getByLabel('Connection name').fill('Claude Code at home');await page.getByRole('button',{name:'Create connection'}).click();
 await page.getByRole('region',{name:'Client setup'}).waitFor();assert.match(await page.locator('pre').textContent(),/--client 87654321/);
 await page.getByRole('button',{name:'Copy setup',exact:true}).click();
 await page.getByRole('button',{name:'Copied',exact:true}).waitFor();
 await page.getByRole('button',{name:'Hide setup',exact:true}).click();
 assert.equal(await page.getByRole('region',{name:'Client setup'}).count(),0);
 const client=page.locator('.settings-row').filter({hasText:'Claude Code at home'});assert.equal(await client.locator('summary').count(),0);await client.getByRole('button',{name:'Configure',exact:true}).click();assert.equal(await client.getByRole('button',{name:'Live access',exact:true}).count(),0);
 await client.getByRole('region',{name:'Client setup'}).waitFor();
 await client.getByRole('button',{name:'Done',exact:true}).click();
 assert.equal(await client.getByRole('region',{name:'Client setup'}).count(),0);
 await client.getByRole('button',{name:'Configure',exact:true}).click();
 await client.getByRole('button',{name:'Disconnect',exact:true}).click();await client.getByRole('button',{name:'Reconnect'}).waitFor();
 assert.equal(await client.getByText('Access revoked',{exact:true}).count(),1);await client.getByRole('button',{name:'Reconnect',exact:true}).click();await client.getByText('Authorized',{exact:true}).waitFor();
 await client.getByText('Not used yet',{exact:true}).waitFor();
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('workbench-client-connected',{detail:'87654321'})));
 await client.getByText(/^Last used /).waitFor();
 assert.equal(await client.getByRole('region',{name:'Client setup'}).count(),0,'setup disappears only when that client connects');
 const legacy=page.locator('.settings-row').filter({hasText:'Claude Code plugin'});
 await legacy.getByRole('button',{name:'Replace connection'}).click();
 const replacement=page.locator('.settings-row').filter({hasText:'Replacement Claude'});
 await replacement.getByRole('region',{name:'Client setup'}).waitFor();
 await legacy.getByText('Authorized',{exact:true}).waitFor();
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('workbench-client-connected',{detail:'22222222'})));
 await replacement.getByText(/^Last used /).waitFor();
 assert.equal(await replacement.getByRole('region',{name:'Client setup'}).count(),0);
 await legacy.waitFor({state:'detached'});
 await page.screenshot({path:'/tmp/bb-connected-clients.png'});
 await page.locator('.rail').getByRole('button',{name:'connected agents',exact:true}).click();
 await page.getByRole('button',{name:'New environment +',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Configure Codex settings',exact:true}).count(),0);
 await page.goto(`${base}/sidebar-workbench.html?same-name-clients=1#/settings/connected-clients`);
 const direct=page.locator('.settings-card').filter({hasText:'Connection 44444444'});
 const migrated=page.locator('.settings-card').filter({hasText:'Connection 55555555'});
 await direct.getByText('Authorized',{exact:true}).waitFor();
 await migrated.getByText('Authorized',{exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Claude Code',exact:true}).count(),2,'same-name credentials remain separate');
 await direct.getByText('Connection 44444444 · Manual setup',{exact:true}).waitFor();
 await migrated.getByText('Connection 55555555 · Legacy plugin replacement',{exact:true}).waitFor();
 assert.notEqual(await direct.getByText(/^Last used /).textContent(),await migrated.getByText(/^Last used /).textContent(),'each credential shows its own activity');
 assert.equal(await page.getByText('Connected',{exact:true}).count(),0,'historical activity is not presented as a live connection');
 await page.setViewportSize({width:600,height:1000});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'connection metadata fits narrow layouts');
 await page.screenshot({path:'/tmp/bb-client-identities.png'});
 await direct.getByRole('button',{name:'Configure',exact:true}).click();
 await direct.getByRole('button',{name:'Disconnect',exact:true}).click();
 await direct.getByText('Access revoked',{exact:true}).waitFor();
 await migrated.getByText('Authorized',{exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Claude Code',exact:true}).count(),2,'revoking one credential preserves the other');
 assert.deepEqual(errors,[]);console.log('Connected Clients: production shell passed');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
