const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const base=process.env.SIDEBAR_PREVIEW_URL||'http://127.0.0.1:5238';
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[],apiRequests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/integration-accounts'))apiRequests.push(r.url());});
  await page.goto(`${base}/sidebar-workbench.html?gmail#/integrations`);
  await page.getByRole('heading',{name:'Library',exact:true}).waitFor();
  const gmailCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Gmail',exact:true})});
  await gmailCard.getByRole('button',{name:'+ Add',exact:true}).click();
  const gmail=page.getByRole('region',{name:'email accounts'});
  await gmail.getByLabel('Email address',{exact:true}).fill('sample@example.com');
  await gmail.getByLabel('App password',{exact:true}).fill('wrong');
  await gmail.getByRole('button',{name:'Connect',exact:true}).click();
  await gmail.getByRole('alert').filter({hasText:'sample app password'}).waitFor();
  await gmail.getByLabel('App password',{exact:true}).fill('abcd efgh ijkl mnop');
  await gmail.getByRole('button',{name:'Connect',exact:true}).click();
  await gmail.getByText('Agents only read',{exact:false}).waitFor();
  assert.equal(await gmail.getByRole('checkbox',{name:'Automatic remembering'}).isChecked(),false);
  await gmail.getByRole('checkbox',{name:'Live access',exact:true}).check();
  await gmail.getByRole('button',{name:'Save',exact:true}).click();
  assert.equal(await gmail.getByRole('checkbox',{name:'Automatic remembering'}).isChecked(),false);
  await gmail.getByRole('checkbox',{name:'Automatic remembering'}).check();
  await gmail.getByRole('button',{name:'Save',exact:true}).click();
  await gmail.getByRole('alert').filter({hasText:'Write what BigBrain should remember'}).waitFor();
  await gmail.getByLabel('What should BigBrain remember?').fill('Remember project decisions; skip routine notifications.');
  await gmail.getByText('History and attachments',{exact:true}).click();
  assert.equal(await gmail.getByRole('checkbox',{name:'Include attachments in future imports'}).isChecked(),false);
  await gmail.getByRole('checkbox',{name:'Import earlier mail'}).check();
  assert.equal(await gmail.getByRole('button',{name:'Save',exact:true}).isDisabled(),false,'Save explains instead of greying out');
  await gmail.getByRole('button',{name:'Save',exact:true}).click();
  await gmail.getByRole('alert').filter({hasText:'Enter the date to remember mail since'}).waitFor();
  await gmail.getByLabel('Remember mail since',{exact:true}).fill('2026-13-40');
  await gmail.getByRole('button',{name:'Save',exact:true}).click();
  await gmail.getByRole('alert').filter({hasText:'YYYY-MM-DD'}).waitFor();
  await gmail.getByLabel('Remember mail since',{exact:true}).fill('2026-09-01');
  await gmail.getByRole('button',{name:'Save',exact:true}).click();
  await gmail.locator('.actions',{has:page.getByRole('button',{name:'Save',exact:true})}).getByRole('status').filter({hasText:'Saved.'}).waitFor();
  await gmail.getByText('Mail since 2026-09-01',{exact:false}).waitFor();
  await page.screenshot({path:'/private/tmp/gmail-setup-desktop.png',fullPage:true});
  await gmail.getByRole('button',{name:'New account +',exact:true}).click();
  await gmail.getByLabel('Email address',{exact:true}).fill('sample@example.com');
  await gmail.getByLabel('App password',{exact:true}).fill('abcd efgh ijkl mnop');
  await gmail.getByRole('button',{name:'Connect',exact:true}).click();
  await gmail.getByRole('alert').filter({hasText:'already exists'}).waitFor();
  assert.equal(await gmail.locator('.account-row').count(),1,'a configured inbox is always listed');
  await gmail.getByRole('button',{name:'Remove…',exact:true}).click();
  await gmail.getByRole('button',{name:'Keep',exact:true}).click();
  assert.equal(await gmail.locator('.account-row').count(),1,'Keep leaves the inbox alone');
  await gmail.getByRole('button',{name:'Remove…',exact:true}).click();
  await gmail.getByRole('button',{name:'Remove',exact:true}).click();
  await gmail.getByRole('status').filter({hasText:'Removed sample@example.com'}).waitFor();
  assert.equal(await gmail.locator('.account-row').count(),0,'a removed inbox leaves the list');
  await gmail.getByLabel('Email address',{exact:true}).waitFor();
  const granola=page.locator('.installed').filter({has:page.getByRole('heading',{name:'Granola',exact:true})});
  await granola.getByRole('button',{name:'Configure',exact:true}).click();
  await page.getByRole('region',{name:'granola accounts'}).getByRole('button',{name:'Connect',exact:true}).click();
  await page.getByRole('region',{name:'granola accounts'}).getByRole('checkbox',{name:'Automatic remembering'}).waitFor();
  // The contract holds for every source: a built-in slot is not removable, an added account is.
  const granolaRegion=page.getByRole('region',{name:'granola accounts'});
  assert.equal(await granolaRegion.getByRole('button',{name:'Remove…',exact:true}).count(),0,'the built-in Granola slot is disconnected, not removed');
  await granolaRegion.getByRole('button',{name:'New account +',exact:true}).click();
  await granolaRegion.getByLabel('Account name',{exact:true}).fill('Work meetings');
  await granolaRegion.getByRole('button',{name:'Add account',exact:true}).click();
  const added=granolaRegion.locator('.account-row').filter({hasText:'Work meetings'});
  await added.waitFor();
  await added.locator('summary').click();
  await added.getByRole('button',{name:'Remove…',exact:true}).click();
  await added.getByRole('button',{name:'Remove',exact:true}).click();
  await granolaRegion.getByRole('status').filter({hasText:'Removed Work meetings'}).waitFor();
  assert.equal(await granolaRegion.locator('.account-row').count(),1,'an added Granola account can be removed');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/private/tmp/gmail-setup-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  assert.deepEqual(apiRequests,[],'Fixture credentials must never reach the network');assert.deepEqual(errors,[]);
  console.log('Gmail + Granola production-shell setup: desktop/mobile, independent choices, opt-in history, duplicate add refused, remove, no network secrets passed');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
