const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ channel: 'chrome' });
 try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const base = process.env.GRAPH_PREVIEW_URL || 'http://127.0.0.1:5219';
  const go = scene => page.goto(`${base}/dev.html?c=pilots%20pane&s=${scene}&preview=1`);
  await go('overview');
  const pane = page.getByRole('region', { name: 'Active pilots', exact: true }); await pane.waitFor();
  assert.equal(await page.locator('.pilot-row').count(), 4);
  assert.equal(await page.locator('.pilot-row .attention-ring').count(), 2);
  assert.equal(await page.locator('.pilot-row .attention-dot').count(), 2);
  assert.equal(await page.locator('.pilots-trigger .attention-dot').count(), 1);
  assert.equal(await pane.getByText('2 need you', { exact: true }).count(), 0);
  assert.equal(await page.locator('.pilot-row .spinner').count(), 2);
  assert.equal(await page.locator('.pilot-row .pilot-triangle').count(), 4);
  await page.keyboard.press('a'); await pane.waitFor({ state: 'hidden' });
  await page.keyboard.press('a'); await pane.waitFor();
  await page.keyboard.press('j'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'atlas');
  await page.keyboard.press('j'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'paper');
  await page.keyboard.press('k'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'atlas');
  assert.equal(await page.locator('.pilot-row .attention-ring').count(), 2, 'Exploring never clears attention');
  await pane.getByRole('button', { name: 'Open conversation' }).focus();
  await page.keyboard.press('ArrowDown'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'paper');
  await page.keyboard.press('ArrowUp'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'atlas');
  const trigger = page.getByRole('button', { name: /^Pilots/ });
  assert.equal((await trigger.textContent()).trim(), '');
  const triggerBox = await trigger.boundingBox(); assert.equal(triggerBox.width, triggerBox.height);
  await page.screenshot({ path: '/private/tmp/pilots-pane-overview.png', animations: 'disabled' });
  await page.keyboard.press('Enter'); await pane.waitFor({ state: 'hidden' });
  await page.getByRole('region', { name: 'Pilot conversation' }).waitFor();
  await page.getByRole('button', { name: 'Allow read access', exact: true }).click();
  assert.equal(await page.locator('.graph .attention-ring').count(), 1);
  await page.keyboard.press('a'); await pane.waitFor();
  assert.equal(await page.locator('.pilot-row .attention-ring').count(), 1);
  await page.keyboard.press('j'); await page.keyboard.press('Enter');
  const reply = page.getByRole('textbox', { name: 'Reply to pilot' });
  await reply.fill('n and jk are just text here');
  assert.equal(await pane.count(), 0);
  await page.getByRole('button', { name: 'Original dataset', exact: true }).click();
  assert.equal(await page.locator('.graph .attention-ring').count(), 0);
  assert.equal(await page.locator('.pilots-trigger .attention-dot').count(), 0);
  await go('many'); await pane.waitFor();
  await page.keyboard.press('End');
  assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'extra-7');
  assert.ok(await page.locator('.roster').evaluate(el => el.scrollTop > 0));
  await page.keyboard.press('Home'); assert.equal(await page.locator('.pilot-row.selected').getAttribute('data-pilot'), 'atlas');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.attention-ring').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.setViewportSize({ width: 390, height: 844 }); await go('overview'); await pane.waitFor();
  const box = await pane.boundingBox(); assert.ok(box.x >= 0 && box.x + box.width <= 390);
  await page.screenshot({ path: '/private/tmp/pilots-pane-mobile.png', animations: 'disabled' });
  await go('quiet'); await pane.waitFor(); assert.equal(await page.locator('.attention-ring, .attention-dot').count(), 0);
  await go('empty'); await pane.waitFor(); await page.keyboard.press('j'); assert.equal(await page.locator('.pilot-row').count(), 0);
  assert.deepEqual(errors, []);
  console.log('PASS Pilots workbench: n/j/k/Enter/Escape, persistent attention, inline responses, long roster, mobile, quiet/empty, reduced motion');
 } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
