const {chromium}=require('./browserHarness.cjs');
const {spawn}=require('node:child_process');
const {readFileSync}=require('node:fs');
const assert=require('node:assert/strict');
const child=spawn('bun',['test/support/sharedWorkspaceFixture.ts'],{stdio:['pipe','pipe','pipe']});
let output='',errors='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>errors+=b);
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let browser;try{
 for(let i=0;!output.includes('\n')&&i<150;i++){if(child.exitCode!==null)throw Error(errors);await pause(100);}
 const fixture=JSON.parse(readFileSync(output.trim().split('\n')[0],'utf8'));
 for(let i=0;i<100;i++){try{if((await fetch(fixture.base+'/api/vault')).ok)break;}catch{}await pause(100);}
 browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
 await page.goto(fixture.base+'/#sharedVaultSettings');await page.getByRole('button',{name:'+ Connect vault',exact:true}).click();await page.getByLabel('Invite link',{exact:true}).fill(fixture.invite);await page.getByRole('dialog').getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});await page.goto(fixture.base+'/#sharedVaultSettings');await page.getByRole('button',{name:'Example team',exact:true}).last().click();
 await page.getByRole('button',{name:'Members',exact:true}).click();await page.getByRole('button',{name:'Invite someone',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Mara Example');await page.getByRole('button',{name:'Create invite link'}).click();const link=await page.getByLabel('Invite link',{exact:true}).inputValue();assert(!link.includes(fixture.token));await page.getByRole('button',{name:'Done',exact:true}).click();
 // An independent local connection store redeems the new member's link.
 const result=spawn('bun',['-e',"import {connectInvite} from './lib/sharedConnections'; const c=await connectInvite(process.argv[1],process.argv[2]); console.log(JSON.stringify(c));",fixture.home+'/recipient-connections.json',link],{stdio:['ignore','pipe','pipe']});let received='';result.stdout.on('data',b=>received+=b);await new Promise((resolve,reject)=>result.on('exit',code=>code===0?resolve():reject(Error('Recipient failed'))));const recipient=JSON.parse(received);assert.equal(recipient.identity.role,'member');assert.notEqual(recipient.identity.handle,'owner');
 await page.getByRole('button',{name:/Added by you/}).click();await page.getByRole('button',{name:'Members',exact:true}).click();await page.getByLabel('Access for Mara Example').waitFor();await page.screenshot({path:fixture.home+'/members.png'});
 const stored=JSON.parse(readFileSync(fixture.home+'/recipient-connections.json','utf8'))[0];const remote=(path,body)=>fetch(fixture.endpoint+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+stored.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
 await page.getByLabel('Access for Mara Example').selectOption('Read only');await page.waitForFunction(()=>document.querySelector('select[aria-label="Access for Mara Example"]')?.value==='Read only');assert.equal((await remote('/v1/evidence',{title:'Denied',body:'Read-only cannot write.'})).status,403);
 await page.getByLabel('Access for Mara Example').selectOption('Can contribute');await page.waitForFunction(()=>document.querySelector('select[aria-label="Access for Mara Example"]')?.value==='Can contribute');assert.equal((await remote('/v1/evidence',{title:'Example contribution',body:'Fabricated content.'})).status,201);
 const row=page.locator('.row').filter({hasText:'Mara Example'});await row.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('button',{name:'Remove member'}).click();await page.getByLabel('Access for Mara Example').waitFor({state:'detached'});assert.equal((await remote('/v1/whoami')).status,401);
 await page.getByRole('button',{name:'Invite someone',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Ren Example');await page.getByRole('button',{name:'Create invite link'}).click();const cancelled=await page.getByLabel('Invite link',{exact:true}).inputValue();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Cancel invite'}).click();await page.getByRole('button',{name:'Cancel invite'}).waitFor({state:'detached'});assert.equal((await fetch(fixture.endpoint+'/v1/invites/redeem',{method:'POST',headers:{Authorization:'Bearer '+new URL(cancelled).hash.slice(1)}})).status,401);
 await page.getByRole('button',{name:'Example team',exact:true}).first().click();await page.getByRole('button',{name:'Members',exact:true}).click();await page.getByText('Full access',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Invite someone',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Remove',exact:true}).count(),0);assert.equal(await page.getByRole('combobox').count(),0);
 assert.deepEqual(pageErrors,[]);console.log('PASS: real owner UI → invitation → independent recipient → access changes → removal; cancelled invitation rejected. Screenshot: '+fixture.home+'/members.png');
 }finally{await browser?.close();child.kill('SIGTERM');}})().catch(e=>{console.error(e);process.exitCode=1;});
