// Run Vite first. Production AppShell with the synthetic graph fixture.
const { chromium } = require('./browserHarness.cjs');
const assert = require('node:assert/strict');
const base = process.env.SIDEBAR_PREVIEW_URL || 'http://127.0.0.1:5200';
(async () => {
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    context.on('page', p => p.on('pageerror', e => errors.push(e.stack)));
    const page = await context.newPage();
    const canvas = page.locator('.lg-wrap > canvas:not([aria-hidden])');
    const presentation = () => canvas.evaluate(c => c.profilePresentation());
    const camera = async () => (await presentation()).camera;
    const ready = () => page.waitForFunction(() => document.querySelector('.graph-renderer canvas')?.profilePresentation?.().nodes.length > 0);
    const settle = () => page.waitForTimeout(2000);
    await page.goto(`${base}/sidebar-workbench.html`);
    await canvas.waitFor(); await settle();
    await ready();
    const before = await presentation();
    const initialCamera = await camera();
    const graphBox = await canvas.boundingBox();
    assert.equal(graphBox.x, 0, 'graph uses the whole window');
    assert.equal(await page.locator('.graph-renderer').getAttribute('data-renderer'), 'webgl');
    const home = async () => {
      if (await page.locator('#topbar input').evaluateAll(els=>els.some(el=>el===document.activeElement))) await page.keyboard.press('Escape');
      await page.keyboard.press('Escape');
      await page.waitForFunction(() => location.hash === '#/home' && document.documentElement.dataset.sidebarWorkbench === 'closed');
    };
    const memoryLabel = before.labels.find(label => before.nodes.some(n => n.id === label.id && n.group === 'memory'));
    assert(memoryLabel, 'home exposes a memory label');
    await page.mouse.move(memoryLabel.left + memoryLabel.width / 2, memoryLabel.top + memoryLabel.height / 2);
    await page.waitForFunction(id => document.querySelector('.graph-renderer').dataset.hovered === id, memoryLabel.id);
    assert.equal((await presentation()).hovered, memoryLabel.id, 'memory label itself is hoverable');
    await page.mouse.click(memoryLabel.left + memoryLabel.width / 2, memoryLabel.top + memoryLabel.height / 2);
    await page.waitForFunction(id => document.querySelector('.graph-renderer canvas').profilePresentation().view.selected.includes(id), memoryLabel.id);
    await home(); await page.mouse.move(1400, 930); await settle();

    assert((await presentation()).nodes.find(n => n.id === 'pilot-11111111111111111111111111111111').visible, 'active agent stays discoverable in the overview');
    assert.equal((await presentation()).nodes.find(n => n.id === 'pilot-22222222222222222222222222222222').visible, true, 'idle agent remains visible on the foreground layer');
    await page.mouse.move(1400, 930);
    await page.waitForTimeout(2800);
    assert.equal(await page.locator('html').getAttribute('data-sidebar-toolbar'), 'false', 'idle home hides toolbar');
    await page.mouse.move(1390, 920);
    assert.equal(await page.locator('html').getAttribute('data-sidebar-toolbar'), 'true', 'mouse movement reveals toolbar');
    const searchButton = page.getByRole('button', { name: 'Search', exact: true });
    // Retain toolbar focus while a slow renderer completes click actionability.
    await searchButton.focus();
    await searchButton.click();
    await page.getByRole('combobox', { name: 'Search the vault' }).waitFor();
    assert(await page.locator('.sidebar-search-trigger').evaluate(el => getComputedStyle(el).borderTopColor !== 'rgba(0, 0, 0, 0)'), 'search shows its active tab outline');
    await page.getByRole('button', {name:'Settings', exact:true}).click();
    await page.locator('#main > .settings').waitFor();
    await page.waitForTimeout(300); // Let the search field collapse before measuring settings chrome.
    const settingsBox = await page.locator('#main > .settings').boundingBox();
    assert.equal(settingsBox.x, 0); assert.equal(settingsBox.width, 1440);
    assert(settingsBox.y >= 80, 'settings live below toolbar inside panel');
    const settingsRail = await page.locator('.settings > .rail').boundingBox();
    const settingsContent = await page.locator('.settings > .content').boundingBox();
    assert(settingsContent.x > settingsRail.x + settingsRail.width, 'settings categories remain a left sidebar');
    const settingsClose = await page.getByRole('button', {name:'Close sidebar', exact:true}).boundingBox();
    assert(settingsClose.x > 1350 && settingsClose.y < 80, 'close control balances the toolbar at the right');
    assert.equal(await page.locator('.sidebar-close kbd').textContent(), 'Esc');
    assert(await canvas.isVisible(), 'graph stays behind settings');
    assert.equal(await page.locator('html').getAttribute('data-sidebar-tab'), 'settings');
    await page.waitForTimeout(300);
    await page.screenshot({path:'/tmp/sidebar-settings-sample.png'});
    await home();
    // J/K preview memories and their inline agents.
    await page.keyboard.press('j'); await settle();
    const menu = page.locator('.workspace-menu');
    const firstMemory = (await presentation()).view.selected[0];
    assert((await presentation()).nodes.some(n => n.id === firstMemory && n.group === 'memory'));
    await page.keyboard.press('j'); await settle();
    const secondMemory = (await presentation()).view.selected[0];
    await page.keyboard.press('k'); await settle();
    assert.equal((await presentation()).view.selected[0],firstMemory);
    await page.keyboard.press('j'); await settle();
    assert.equal((await presentation()).view.selected[0],secondMemory);
    await menu.getByRole('button',{name:'Component audit Ready'}).waitFor();
    assert.equal(await page.locator('.drawer:not(.sidebar-quick)').count(),0);
    console.log('PASS: settings return, workspace preview and attached-agent menu');
    await page.getByRole('button', {name:'Settings', exact:true}).click();
    await page.locator('#main > .settings').waitFor(); await settle();
    assert.equal(await page.locator('html').getAttribute('data-sidebar-tab'), 'settings');
    assert(await page.locator('#main > .settings').isVisible(), 'selected note cannot navigate away from settings');
    await home();
    await page.keyboard.press('r');
    await page.getByRole('listbox', { name: 'Recently added' }).waitFor();
    await page.waitForTimeout(200);
    assert.equal(await page.locator('#topbar .field').count(),0);
    assert.equal(await page.locator('html').getAttribute('data-sidebar-tab'), 'recents');
    const allRecentCount = await page.getByRole('option').count();
    await page.keyboard.press('u');
    await page.waitForTimeout(300);
    assert.equal(await page.getByRole('button', {name:'Unread u', exact:true}).getAttribute('aria-pressed'), 'true');
    assert((await page.getByRole('option').allTextContents()).every(text => text.includes('Unread')), 'unread filter excludes read and unknown items');
    await page.keyboard.press('u');
    await page.waitForTimeout(300);
    assert.equal(await page.getByRole('option').count(), allRecentCount, 'turning filter off restores all recents');
    let previousRow;
    for (const key of ['j', 'j', 'k', 'ArrowDown', 'ArrowUp']) {
      await page.keyboard.press(key);
      assert.equal(await page.locator('#topbar input').count(),0);
      const row = await page.locator('[role=option][aria-selected=true]').textContent();
      if (previousRow !== undefined) assert.notEqual(row, previousRow, `${key} navigates recents`);
      previousRow = row;
    }
    await page.getByRole('option', { name: 'Atlas', exact: true }).click();
    await page.locator('.drawer:not(.sidebar-quick) .briefing-summary').waitFor();
    await settle();
    assert(await page.locator('.source-links .source-link').count() > 0, 'actual NoteTab connections');
    const after = await presentation();
    assert((await presentation()).nodes.filter(n => n.visible && n.opacity > .3).length > 3, 'opening a note preserves the surrounding graph');
    assert(Math.abs((await camera()).zoom - initialCamera.zoom) < 1e-10, 'selection never changes zoom');
    assert(after.nodes.some(n => Math.abs(n.height - before.nodes.find(p => p.id === n.id).height) > 1), 'selection changes graph depth');
    await page.keyboard.press('j');
    assert.equal(await page.getByRole('listbox').count(), 0, 'J navigates links instead of opening search');
    assert.equal(await page.locator('#topbar input').count(),0);
    await page.locator('.drawer:not(.sidebar-quick) .source-link.lk-on').waitFor();
    const firstLink = await page.locator('.drawer:not(.sidebar-quick) .source-link.lk-on').getAttribute('data-path');
    await page.keyboard.press('j');
    await page.waitForFunction(path => document.querySelector('.drawer:not(.sidebar-quick) .source-link.lk-on')?.getAttribute('data-path') !== path, firstLink);
    await page.keyboard.press('k');
    await page.waitForFunction(path => document.querySelector('.drawer:not(.sidebar-quick) .source-link.lk-on')?.getAttribute('data-path') === path, firstLink);
    await home();
    assert.equal(await page.locator('html').getAttribute('data-sidebar-workbench'), 'closed');
    assert.equal(await page.locator('.drawer:not(.sidebar-quick)').isVisible(), false);
    await page.keyboard.press('/');
    await page.getByRole('combobox', { name: 'Search the vault' }).fill('Atlas');
    assert.equal(await page.getByRole('combobox', { name: 'Search the vault' }).inputValue(), 'Atlas');
    await home(); await page.keyboard.press('/');
    await page.waitForTimeout(200);
    assert.equal(await page.getByRole('listbox').count(),1,'empty search offers recent results');
    assert(await page.getByRole('combobox', { name: 'Search the vault' }).evaluate(el => el === document.activeElement), 'Slash focuses empty search');
    assert.equal(await page.locator('.search-hit.active-pilot').count(),0,'agents excluded from recents');
    await page.getByRole('combobox', { name: 'Search the vault' }).fill('Atlas planning');
    await page.waitForTimeout(300);
    assert.equal(await page.locator('.search-hit.active-pilot').count(),0,'agents excluded from search');
    await home(); await page.keyboard.press('a');
    await page.getByRole('region', { name: 'Agents', exact: true }).waitFor();
    await page.waitForTimeout(2800);
    assert.equal(await page.locator('html').getAttribute('data-sidebar-toolbar'), 'true', 'open sidebar retains toolbar');
    assert.equal(await page.locator('html').getAttribute('data-sidebar-tab'), 'agents');
    assert.equal(await page.locator('.pilots-trigger').evaluate(el => getComputedStyle(el).boxShadow), 'none', 'active tab has only one outline');
    await page.screenshot({path:'/tmp/sidebar-tabs-sample.png'});
    await settle();
    await page.getByRole('button', {name:'Show archived', exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.pilot-row').length===5);
    await page.getByRole('button', {name:'Show archived', exact:true}).evaluate(el=>el.blur());
    const messageTimes = await page.locator('.pilot-row time').evaluateAll(els => els.map(el => Date.parse(el.dateTime)));
    assert(messageTimes.every((time, i) => !i || time <= messageTimes[i - 1]), 'agents use latest-message order');
    const listBox = await page.locator('.pilots-pane').boundingBox();
    assert.equal(listBox.x, 0); assert.equal(Math.round(listBox.width), 560);
    assert.equal(await page.locator('.agent-key').textContent(), 'a');
    assert.equal(await page.locator('.pilot-row').nth(1).locator('.identity-glyph.live').count(), 1, 'recently dormant agent uses the active icon');
    const iconColors = await page.locator('.pilot-row .identity-glyph').evaluateAll(els => els.map(el => getComputedStyle(el).color));
    assert.equal(iconColors[0], iconColors[1],'all active roster icons use the active color');
    await page.keyboard.press('j'); await page.waitForTimeout(300);
    assert.deepEqual((await presentation()).highlighted, [await page.locator('.pilot-row.selected').getAttribute('data-pilot')], 'agent navigation highlights its graph neighborhood');
    await page.keyboard.press('ArrowDown'); await page.waitForTimeout(300);
    assert.deepEqual((await presentation()).highlighted, [await page.locator('.pilot-row').nth(1).getAttribute('data-pilot')], 'idle agents can be highlighted from the list');
    await page.locator('.pilot-row').first().click();
    await page.locator('.pilot-panel').waitFor();
    const headerTitle = await page.locator('.pilot-panel header > strong').boundingBox();
    const model = await page.locator('.pilot-panel .model-command').boundingBox();
    assert(Math.abs(model.x - headerTitle.x) < 6, 'model is aligned beneath the chat title');
    await page.locator('.pilot-panel .model-command').click();
    await page.getByRole('button', {name:'Close model settings', exact:true}).click();
    await page.waitForFunction(() => !document.querySelector('.backend-settings'));
    assert(model.y > headerTitle.y + headerTitle.height, 'model sits on a separate row under title');
    assert.equal(await page.locator('.pilot-panel header').getByRole('button', {name:/Send/}).count(), 0, 'send belongs beside composer');
    assert.equal(await page.locator('.pilot-panel .composer-actions button').count(), 1);
    assert.equal(await page.getByRole('button', {name:'Archive Pilot', exact:true}).getAttribute('aria-keyshortcuts'), 'Shift+Escape');
    assert.equal(await page.locator('.resize-controls').count(),0,'chat has no collapse controls');
    await page.locator('.pilot-panel .editor').fill('Keep this draft');
    await page.keyboard.press('Shift+ArrowLeft');
    await page.keyboard.press('Alt+h');
    assert.equal(Math.round((await page.locator('.chat-drawer').boundingBox()).width),1440);
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => document.documentElement.dataset.sidebarWorkbench === 'closed');
    assert.equal(await page.locator('.pilots-pane').count(), 0, 'Escape returns directly home without the agents bar');
    assert.equal(await page.locator('.chat-drawer').isVisible(), false);

    assert.equal(new URL(page.url()).hash, '#/home', 'Escape returns home');
    await page.keyboard.press('a');
    const archivedPilotId = await page.locator('.pilot-row').first().getAttribute('data-pilot');
    await page.locator('.pilot-row').first().click();
    await page.locator('.pilot-panel .editor').waitFor();
    assert.equal(await page.locator('.pilot-panel .editor').textContent(), 'Keep this draft');
    assert((await presentation()).edges.some(e => e.source === archivedPilotId || e.target === archivedPilotId), 'active pilot has context edges');
    await page.keyboard.press('Shift+Escape');
    await page.waitForFunction(() => document.documentElement.dataset.sidebarWorkbench === 'closed');
    assert.equal(await page.locator('.pilot-panel').count(), 0, 'Shift-Esc stops the sample session and returns home');
    await page.waitForFunction(id => {
      const graph = document.querySelector('.graph-renderer canvas').profilePresentation();
      return graph.nodes.some(n => n.id === id && n.phase === 'idle') && !graph.edges.some(e => e.source === id || e.target === id);
    }, archivedPilotId);
    console.log('PASS: recents/search, agent navigation, chat shortcuts, and draft retention');
    // Inspect the production GPU presentation, and exercise real pointer/navigation paths.
    await page.goto(`${base}/sidebar-workbench.html`);
    await ready(); await settle();
    const beforeHoverCamera = await camera();
    const overview = await presentation();
    const label = overview.labels.find(label => overview.nodes.some(n => n.id === label.id && n.group === 'memory'));
    assert(label, 'sample offers a memory label');
    await page.mouse.move(label.left + label.width / 2, label.top + label.height / 2);
    await page.waitForFunction(id => document.querySelector('.graph-renderer').dataset.hovered === id, label.id);
    await page.locator('.sidebar-quick .briefing-summary').waitFor();
    const hoveredTitle = await page.locator('.sidebar-quick .note-title').textContent();
    const hover = await presentation();
    assert.equal(hover.hovered, label.id);
    assert.deepEqual(hover.view.selected, [], 'hover does not commit selection');
    assert.deepEqual(hover.camera, beforeHoverCamera, 'hover keeps the camera stationary');
    assert(hover.nodes.filter(n => n.visible).length > 3, 'hover preserves the surrounding graph');
    await page.mouse.move(-10, -10);
    await page.waitForFunction(() => document.querySelector('.graph-renderer canvas').profilePresentation().hovered === null);
    await page.locator('.sidebar-quick').waitFor({state:'hidden'});
    assert.deepEqual((await presentation()).view.selected, [], 'leaving hover preserves the overview');
    await page.mouse.move(720, 850);
    await page.mouse.wheel(0, -240);
    await page.waitForFunction(zoom => document.querySelector('.graph-renderer canvas').profilePresentation().camera.zoom !== zoom, beforeHoverCamera.zoom);
    await home(); await settle();
    assert.deepEqual((await presentation()).view, {selected:[], excluded:[]}, 'Escape restores the default graph view');
    const resetCamera = await camera();
    for (const axis of ['zoom', 'x', 'y']) assert(Math.abs(resetCamera[axis] - beforeHoverCamera[axis]) < .01, 'Escape restores overview framing');
    await page.keyboard.press('/');
    await page.getByRole('combobox', {name:'Search the vault'}).fill(hoveredTitle);
    const result = page.getByRole('option', {name:hoveredTitle, exact:true});
    await result.hover(); await settle();
    assert.deepEqual((await presentation()).view.selected, [label.id], 'search previews the chosen item');
    await result.click(); await settle();
    const committed = await presentation();
    assert.deepEqual(committed.view.selected, [label.id], 'opening the result commits its selection');
    assert(committed.nodes.filter(n => n.visible).length > 3, 'selection preserves the surrounding graph');
    assert(overview.nodes.filter(n => n.phase && n.visible).every(n => committed.nodes.find(p => p.id === n.id).visible), 'Pilots visible at home remain discoverable after selection');
    assert.deepEqual(errors, []);
    console.log('PASS: GPU label picking, hover, zoom/reset, search selection and production-shell navigation');
    await page.goto(`${base}/sidebar-workbench.html?annotations`);
    await ready(); await settle();
    await page.keyboard.press('r');
    const clipRow = page.getByRole('option', { name: 'Workshop report', exact: true });
    const noteRow = page.getByRole('option', { name: 'Recommended by a colleague', exact: true });
    await noteRow.waitFor();
    assert.equal(await noteRow.locator('.hit-kind').textContent(), 'Note');
    assert.equal(await clipRow.locator('.hit-kind').textContent(), 'source');
    assert(await noteRow.evaluate(el => el.classList.contains('annotation')));
    assert.equal(await noteRow.evaluate(el => el.previousElementSibling?.textContent.includes('Workshop report')), true);
    assert.equal(await noteRow.locator('.hit-title').evaluate(el => getComputedStyle(el).paddingLeft), '28px');
    await noteRow.click();
    await page.waitForFunction(() => location.hash.includes('sources/sample-note.md'));
    assert.deepEqual(errors, []);
    console.log('PASS: follow-on annotations nest beneath their source and remain openable');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
