const { webkit } = require('playwright-core');
const assert = require('node:assert/strict');
const base = process.env.PROFILE_URL || 'http://127.0.0.1:53490';
(async () => {
  const browser = await webkit.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 2 });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.route('**/api/**', route => route.abort());
    await page.goto(`${base}/sidebar-workbench.html?profile=1&graphEffects=none`);
    await page.waitForFunction(() => document.querySelector('.graph-renderer canvas')?.width === innerWidth * devicePixelRatio);
    const canvas = page.locator('.graph-renderer canvas');
    assert.equal(await page.locator('.lg-wrap canvas').count(), 1);
    assert.equal(await page.getByRole('alert').count(), 0);
    const stats = () => canvas.evaluate(c => ({ ...c.profileStats }));
    const initial = await stats();
    await page.keyboard.press('j'); await page.waitForTimeout(60);
    const first = await page.locator('.graph-renderer').getAttribute('data-selected');
    await page.keyboard.press('j'); await page.waitForTimeout(60);
    const second = await page.locator('.graph-renderer').getAttribute('data-selected');
    assert(first && second && first !== second, 'j changes renderer selection');
    await page.keyboard.press('k'); await page.waitForTimeout(1200);
    assert.equal(await page.locator('.graph-renderer').getAttribute('data-selected'), first, 'k returns to previous selection');
    const settled = await stats();
    const selectedPoint = await canvas.evaluate((c, id) => c.profilePresentation().nodes.find(n => n.id === id), first);
    assert(selectedPoint && selectedPoint.x >= 79 && selectedPoint.x <= 1361 && selectedPoint.y >= 79 && selectedPoint.y <= 921, 'selected memory is visible within the safe frame');
    assert.equal(settled.uploads - initial.uploads, 3, 'one target upload per selection change');
    assert.equal(settled.drawCalls, settled.frames * 4 + settled.activityDrawCalls, 'four graph batches plus one optional activity batch');
    await page.emulateMedia({ reducedMotion: 'reduce' }); await page.waitForTimeout(1200);
    const resting = await stats();
    await page.waitForTimeout(300);
    assert.equal((await stats()).frames, resting.frames, 'renderer sleeps with static reduced-motion signals');
    await page.setViewportSize({ width: 1000, height: 800 });
    await page.waitForFunction(() => document.querySelector('.graph-renderer canvas').width === 2000);
    assert.equal((await stats()).uploads, resting.uploads, 'resize does not reupload geometry/selection');
    await canvas.evaluate(c => { c.profileLoss = c.getContext('webgl2').getExtension('WEBGL_lose_context'); c.profileLoss.loseContext(); });
    await page.getByRole('alert').waitFor();
    await canvas.evaluate(c => { c.profileLoss.restoreContext(); });
    await page.waitForFunction(() => !document.querySelector('.graph-renderer [role="alert"]'));
    await page.keyboard.press('j'); await page.waitForTimeout(400);
    assert.equal(await page.locator('.graph-renderer').getAttribute('data-selected'), second);
    const recovered = await stats(); assert(recovered.frames > 0 && recovered.nodes > 0);
    await page.getByRole('button', { name: 'Run j/k profile' }).click();
    await page.getByRole('button', { name: 'Run j/k profile' }).waitFor({ timeout: 15000 });
    const profile = JSON.parse(await page.getByRole('textbox', { name: 'Profiling result' }).inputValue());
    assert.equal(profile.renderer, 'webgl'); assert(profile.samples > 20);
    await page.screenshot({ path: '/tmp/unified-graph-sample.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: one canvas, j/k selection, interrupted transitions, upload counts, sleep, DPR2 resize, context recovery, production-shell comparison panel');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
