const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ channel: 'chrome' });
 try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const base = process.env.GRAPH_PREVIEW_URL || 'http://127.0.0.1:5219';
  await page.goto(base + '/dev.html?c=unread%20sources&s=crowded&preview=1');
  await page.getByText('60 unread', { exact: true }).waitFor();
  await page.waitForTimeout(1500);
  await page.screenshot({ path: '/private/tmp/unread-sources-crowded.png' });
  await page.getByRole('button', { name: 'Find an unread source' }).click();
  await page.getByRole('region', { name: 'Source text tab' }).waitFor();
  assert.equal(await page.getByText('60 unread', { exact: true }).count(), 1, 'Opening preserves unread state');
  await page.waitForTimeout(600);
  await page.screenshot({ path: '/private/tmp/unread-source-text-tab.png' });
  const tab = page.getByRole('region', { name: 'Source text tab' });
  assert.equal(await tab.getByRole('button', { name: /PILOT/ }).count(), 1);
  assert.equal(await tab.getByText('DISCUSS', { exact: true }).count(), 0);
  assert.equal(await tab.getByRole('button', { name: 'MARK READ', exact: true }).getAttribute('aria-keyshortcuts'), 'Shift+U');
  await page.keyboard.press('u');
  assert.equal(await page.getByText('60 unread', { exact: true }).count(), 1);
  await page.evaluate(() => { const input = document.createElement('input'); input.id = 'shortcut-typing-test'; document.body.append(input); input.focus(); });
  await page.keyboard.press('Shift+U');
  assert.equal(await page.getByText('60 unread', { exact: true }).count(), 1, 'Typing does not toggle source state');
  await page.evaluate(() => document.querySelector('#shortcut-typing-test').remove());
  await page.keyboard.press('Shift+U');
  await page.getByText('59 unread', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'MARK UNREAD', exact: true }).waitFor();
  await page.keyboard.press('Shift+U');
  await page.getByText('60 unread', { exact: true }).waitFor();
  await page.getByRole('checkbox', { name: 'Show indicators' }).uncheck();
  await page.getByRole('checkbox', { name: 'Show indicators' }).check();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(base + '/dev.html?c=unread%20sources&s=many&preview=1');
  await page.getByText('149 unread', { exact: true }).waitFor();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '/private/tmp/unread-sources-many.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(700);
  await page.screenshot({ path: '/private/tmp/unread-sources-mobile.png' });
  await page.goto(base + '/dev.html?c=unread%20sources&s=quiet&preview=1');
  await page.getByText('0 unread', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Find an unread source' }).isDisabled(), true);
  assert.deepEqual(errors, []);
  console.log('Unread sources workbench: crowded/many/quiet, read toggles, reduced motion and mobile passed.');
 } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
